# Generated by Django 5.1 on 2024-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_respuesta_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='valor',
            field=models.IntegerField(choices=[(1, 'Muy en desacuerdo'), (2, 'En desacuerdo'), (3, 'Ni de acuerdo ni en desacuerdo'), (4, 'De acuerdo'), (5, 'Muy de acuerdo')]),
        ),
    ]
